CREATE OR REPLACE VIEW public.untappd_checkin
AS SELECT 
	untappd.checkin_id,
	untappd.created_at,
	untappd.beer_name,
    untappd.brewery_name,
    untappd.venue_name,
    untappd.purchase_venue,
    untappd.serving_type,
    untappd.beer_type,
    untappd.beer_abv,
    untappd.beer_ibu,
    untappd.comment,
    untappd.venue_city,
    untappd.venue_state,
    untappd.venue_country,
    untappd.venue_lat,
    untappd.venue_lng,
    untappd.rating_score,
    untappd.checkin_url,
    untappd.beer_url,
    untappd.brewery_url,
    untappd.brewery_country,
    untappd.brewery_city,
    untappd.brewery_state,
    untappd.flavor_profiles,
    untappd.bid,
    untappd.brewery_id,
    untappd.photo_url,
    untappd.global_rating_score,
    untappd.global_weighted_rating_score,
    untappd.tagged_friends,
    untappd.total_toasts,
    untappd.total_comments,
    cast(to_char(untappd.created_at, 'YYYYMMDD') as int) as created_day
   FROM untappd;